# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
#   push:
#     branches: [ "master" ]
#   pull_request:
#     branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


env:
  IMAGE_TAG: ${{github.run_id}}
  IMAGE_NAME: anwink/k8splayground
  
jobs:
  # This workflow contains a single job called "build"
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload the artifact to github
        uses: actions/upload-artifact@v3
        with:
          name: springboot-k8s-yaml-main-jar
          path: |
            ./target/springboot-k8s-demo.jar
            ./Dockerfile

  download-and-deploy-dev:
    name: Download the Deploy
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Download the artifact from build-and-push
        uses: actions/download-artifact@v3
        with:
          name: springboot-k8s-yaml-main-jar
      
      - name: print the dir details
        run: |
          pwd
          ls -la

      # - name: Push DEV container to docker hub
      #   uses: mr-smithers-excellent/docker-build-push@v5
      #   with:
      #     image: $IMAGE_NAME
      #     tags: ${{ format('{0}-{1}', env.IMAGE_TAG, 'latest') }}
      #     registry: acrazewtmaeu0001dapodm.azurecr.io
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: acrazewtmaeu0001dapodm.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build docker image
        run: |
          docker build -t springboot-k8s-yaml-main:1.0 .
          docker images
          docker push acrazewtmaeu0001dapodm.azurecr.io/springboot-k8s-yaml-main:1.0

