# This is a basic workflow to help you get started with Actions

name: K8s Secret

on:
  workflow_dispatch:

env:
  AZ_AKS_NAME: dap-np-west-1
  AZ_AKS_NAMESPACE: dap-dev
  AZ_RG_NAME: rgpazewdaks01dapdev
  
jobs:
  # This workflow contains a single job called "build"
  deploy-to-k8s:
    name: Create a secret
    runs-on: ubuntu-latest

    steps:
      - name: Connect to AKS Cluster
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.DEV_AKS_AZURE_SP }}'
          cluster-name: ${{ env.AZ_AKS_NAME }}
          resource-group: ${{ env.AZ_RG_NAME }}

      - name: Print all K8s Pods
        run: |  
          kubectl get pods --namespace ${{ env.AZ_AKS_NAMESPACE }}
      
      - name: Apply the deployment manifest
        run: |  
          kubectl create secret generic lov-kafka-dev-secret \
            --from-literal=lov-kafka-dev-user=${{ secrets.LOV_KAFKA_DEV_USER }} \
            --from-literal=lov-kafka-schema-dev-password=${{ secrets.LOV_KAFKA_SCHEMA_DEV_PASSWORD }} \
            --namespace ${{ env.AZ_AKS_NAMESPACE }}